flowchart TD
node0:::executed@{ shape: circle, label: "Start"}
subgraph node1 [" "]
node2["Run Pending Checks"]
node0 --> node2
node3@{ shape: hex, label: "All checks completed?"}
node2 --> node3
node4@{ shape: stadium, label: "fa:fa-clock Await Retry (20s)"}
node3 -->|"No"| node4
node4 --> node2
end
node7@{ shape: stadium, label: "fa:fa-clock Execution Timeout (2m)"}
node1 --> node7
node8@{ shape: hex, label: "Requires review?"}
node7 --> node8
node3 -->|"Yes"| node8
node9@{ shape: stadium, label: "fa:fa-envelope Review Decision"}
node10["Handle Review Decision"]
node9 --> node10
node8 -->|"Yes"| node9
node11["System Decision"]
node8 -->|"No"| node11
classDef executed fill:#0e0
