flowchart TD
node0@{ shape: circle, label: "Start"}
node1@{ shape: stadium, label: "fa:fa-envelope Create Withdrawal"}
node0 --> node1
node2["Validate"]
node1 --> node2
node3["@dynamic"]
node2 --> node3
node4["Cancel Funds If Needed"]
node2 -.->|"fa:fa-bolt Invalid Input"| node4
node3 -.->|"fa:fa-bolt Withdrawal Rejection"| node4
classDef executed fill:#0e0
classDef checkpoint fill:transparent,stroke-dasharray:5 5,stroke:black
classDef checkpoint-executed fill:transparent,stroke-dasharray:5 5,stroke:#0e0
