FROM sbtscala/scala-sbt:eclipse-temurin-17.0.6_10_1.9.6_3.3.1 as builder

WORKDIR /app
COPY . .
RUN sbt "workflows4s-example/assembly"

FROM eclipse-temurin:17-jre-alpine

WORKDIR /app
COPY --from=builder /app/workflows4s-example/target/scala-3.7.0/workflows4s-example-assembly-*.jar /app/app.jar

EXPOSE 8081
CMD ["java", "-jar", "/app/app.jar"]