# Fly.io configuration for the UI server
app = "workflows4s-ui"
primary_region = "ams"  

[build]
  dockerfile = "Dockerfile.ui"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256