flowchart TD
node0@{ shape: circle, label: "Start"}
node1["Do Things With Description"]
node0 --> node1
node2@{ shape: braces, label: "This operation increments the counter by one"}
node1 -.- node2
node3@{ shape: circle, label: "End"}
node1 --> node3
