addSbtPlugin("org.scalameta"  % "sbt-scalafmt"   % "2.4.6")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"   % "0.13.0")
addSbtPlugin("com.github.sbt" % "sbt-dynver"     % "5.0.1")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.5.12")
addSbtPlugin("org.typelevel"  % "sbt-tpolecat"   % "0.5.2")
