flowchart TD
node0:::executed@{ shape: circle, label: "Start"}
subgraph node1 [" "]
node2:::executed@{ shape: stadium, label: "fa:fa-envelope Create Withdrawal"}
node0 --> node2
node3["Validate"]:::executed
node2 --> node3
node4["Calculate Fees"]
node3 --> node4
node5["Put Funds On Hold"]
node4 --> node5
subgraph node6 [" "]
node7["Run Pending Checks"]
node5 --> node7
node8@{ shape: hex, label: "All checks completed?"}
node7 --> node8
node9@{ shape: stadium, label: "fa:fa-clock Await Retry (20s)"}
node8 -->|"No"| node9
node9 --> node7
end
node17@{ shape: stadium, label: "fa:fa-clock Execution Timeout (2m)"}
node6 --> node17
node18["Put In Review"]
node17 --> node18
node19@{ shape: hex, label: "Requires review?"}
node18 --> node19
node8 -->|"Yes"| node19
node20@{ shape: stadium, label: "fa:fa-envelope Review Decision"}
node21["Handle Review Decision"]
node20 --> node21
node19 -->|"Yes"| node20
node22["System Decision"]
node19 -->|"No"| node22
node23["Act On Decision"]
node21 --> node23
node22 --> node23
node24["fa:fa-redo Initiate Execution"]
node23 --> node24
node25@{ shape: stadium, label: "fa:fa-envelope Execution Completed"}
node24 --> node25
node26["Handle Execution Completed"]
node25 --> node26
end
node29@{ shape: stadium, label: "fa:fa-envelope Cancel Withdrawal"}
node1 --> node29
node30["Handle Cancel Withdrawal"]
node29 --> node30
node31["Release Funds"]
node30 --> node31
node26 --> node31
node32["Cancel Funds If Needed"]:::executed
node3 -.->|"fa:fa-bolt Invalid Input"| node32
node5 -.->|"fa:fa-bolt Not Enough Funds"| node32
node23 -.->|"fa:fa-bolt Rejected In Checks"| node32
node24 -.->|"fa:fa-bolt Rejected By Execution Engine"| node32
node26 -.->|"fa:fa-bolt Rejected By Execution Engine"| node32
node30 -.->|"fa:fa-bolt Cancelled"| node32
node33@{ shape: circle, label: "End"}
node31 --> node33
node32 --> node33
classDef executed fill:#0e0
