flowchart TD
node0:::executed@{ shape: circle, label: "Start"}
subgraph node1 [" "]
node2:::executed@{ shape: stadium, label: "fa:fa-envelope Create Withdrawal"}
node0 --> node2
node3["Validate"]:::executed
node2 --> node3
node4["Calculate Fees"]:::executed
node3 --> node4
node5["Put Funds On Hold"]:::executed
node4 --> node5
subgraph node6 [" "]
node7["Run Pending Checks"]
node5 --> node7
node8@{ shape: stadium, label: "fa:fa-clock  (dynamic)"}
node7 --> node8
end
node16@{ shape: stadium, label: "fa:fa-clock  (dynamic)"}
node6 --> node16
node17["Put In Review"]
node16 --> node17
node18@{ shape: hex, label: "Requires review?"}
node17 --> node18
node8 --> node18
node19@{ shape: stadium, label: "fa:fa-envelope Review Decision"}
node20["Handle Review Decision"]
node19 --> node20
node18 -->|"Yes"| node19
node21["System Decision"]
node18 -->|"No"| node21
node22["Act On Decision"]
node20 --> node22
node21 --> node22
node23["Initiate Execution"]
node22 --> node23
node24@{ shape: stadium, label: "fa:fa-envelope Execution Completed"}
node23 --> node24
node25["Handle Execution Completed"]
node24 --> node25
end
node28:::executed@{ shape: stadium, label: "fa:fa-envelope Cancel Withdrawal"}
node1 --> node28
node29["Handle Cancel Withdrawal"]:::executed
node28 --> node29
node30["Release Funds"]
node29 --> node30
node25 --> node30
node31["Cancel Funds If Needed"]:::executed
node3 -.->|"fa:fa-bolt Invalid Input"| node31
node5 -.->|"fa:fa-bolt Not Enough Funds"| node31
node22 -.->|"fa:fa-bolt Rejected In Checks"| node31
node23 -.->|"fa:fa-bolt Rejected By Execution Engine"| node31
node25 -.->|"fa:fa-bolt Rejected By Execution Engine"| node31
node29 -.->|"fa:fa-bolt Cancelled"| node31
node32@{ shape: circle, label: "End"}
node30 --> node32
node31 --> node32
classDef executed fill:#0e0
