# fly.toml app configuration file generated for workflows4s-example on 2025-07-24T07:53:30+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "workflows4s-example"
primary_region = "ams"

[build]
  image = "workflows4s-example:latest"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory = "512mb"

[env]
  JAVA_OPTS = "-Xmx384m -Xms64m -XX:+UseContainerSupport"