flowchart TD
node0@{ shape: circle, label: "Start"}
node1:::checkpoint
subgraph node1 ["Checkpoint"]
node2["My Workflow"]
node0 --> node2
end
classDef executed fill:#0e0
classDef checkpoint fill:transparent,stroke-dasharray:5 5,stroke:black
