flowchart TD
node0@{ shape: circle, label: "Start"}
node1@{ shape: hex, label: "Is counter positive?"}
node0 --> node1
node2["Do A"]
node1 -->|"Yes"| node2
node3["Do B"]
node1 -->|"No"| node3
classDef executed fill:#0e0
classDef checkpoint fill:transparent,stroke-dasharray:5 5,stroke:black
classDef checkpoint-executed fill:transparent,stroke-dasharray:5 5,stroke:#0e0
