flowchart TD
node0:::executed@{ shape: circle, label: "Start"}
node1["Step1"]
node0 --> node1
node2@{ shape: hex, label: "Is everything done?"}
node1 --> node2
node3["Step2"]
node2 -->|"No"| node3
node3 --> node1
classDef executed fill:#0e0
