flowchart TD
node0@{ shape: circle, label: "Start"}
node1@{ shape: fork, label: ""}
node0 --> node1
node2["Do A"]
node1 --> node2
node3["Do B"]
node1 --> node3
node4@{ shape: fork, label: ""}
node2 --> node4
node3 --> node4
classDef executed fill:#0e0
classDef checkpoint fill:transparent,stroke-dasharray:5 5,stroke:black
classDef checkpoint-executed fill:transparent,stroke-dasharray:5 5,stroke:#0e0
