flowchart TD
node0@{ shape: circle, label: "Start"}
node1["Do Things With Description"]
node0 --> node1
node2@{ shape: braces, label: "This operation increments the counter by processing an event"}
node1 -.- node2
