name: Deploy workflows4s-example to Fly.io

on:
  push:
    branches:
      - main # Trigger deployment on every push to the main branch
      - gsoc-2025

jobs:
  deploy-example:
    name: Deploy workflows4s-example
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy example API to Fly.io
        run: flyctl deploy --remote-only --config fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}